FROM openjdk:8-alpine
MAINTAINER openslice.io
COPY target/io.openslice.tmf.api-0.0.1-SNAPSHOT-exec.jar /opt/openslice/lib/
ENV SPRING_APPLICATION_JSON='{ \
	"spring.datasource.url": "dbc:mysql://0.0.2.15/ostmfdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",  \
	"spring.activemq.broker-url": "tcp://10.0.2.15:61616"  }'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/openslice/lib/io.openslice.tmf.api-0.0.1-SNAPSHOT-exec.jar"]
EXPOSE 13082