origins: http://localhost,http://localhost:13082,http://127.0.0.1:13082,https://localhost, 
permit-all: /tmf-api/**


server:
  port: 13082
  servlet:
    context-path : /tmf-api
  error:
    include-message: always
  ssl:
    enabled: false
    
springdoc:
  version: '@springdoc.version@'
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    oauth:
      client-id: osapiWebClientId
      clientsecret: "secret"
      use-pkce-with-authorization-code-grant: false
  oAuthFlow:
    authorizationUrl: http://keycloak:8080/auth/realms/openslice/protocol/openid-connect/auth
    tokenUrl: http://keycloak:8080/auth/realms/openslice/protocol/openid-connect/token
  show-actuator: true

spring-addons:
  issuers:
  - uri: http://keycloak:8080/auth/realms/openslice
    username-json-path: $.preferred_username
    claims:
    - jsonPath: $.realm_access.roles
    - jsonPath: $.resource_access.*.roles

spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: openslice-service-catalog-management-api
  datasource:
    url: jdbc:mysql://localhost:13306/ostmfdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: letmein
    username: root
    hikari:
       minimumIdle: 2
       maximumPoolSize: 40
       idleTimeout: 120000
       connectionTimeout: 400000
       leakDetectionThreshold: 100000
  jpa:
    database-platform: io.openslice.tmf.LocalMysqlDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext 
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true 
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  activemq:
    brokerUrl: tcp://localhost:61616?jms.watchTopicAdvisories=false
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/openslice
  

logging:
  level:
    root: INFO
    portal.api: INFO
    io.openslice.tmf.*: DEBUG
    org.springframework: INFO
    org.apache.camel: INFO 
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
  
    

kroki:
  serverurl: http://localhost:8000

oauthsign:
   key: "EK97Y7Y9WPGG1MEG"

#QUEUE MESSAGES  
CATALOG_GET_SERVICEORDERS: "jms:queue:CATALOG.GET.SERVICEORDERS"
CATALOG_GET_SERVICEORDER_BY_ID: "jms:queue:CATALOG.GET.SERVICEORDER_BY_ID"
CATALOG_ADD_SERVICEORDER: "jms:queue:CATALOG.ADD.SERVICEORDER"
CATALOG_UPD_SERVICEORDER_BY_ID: "jms:queue:CATALOG.UPD.SERVICEORDER_BY_ID"
CATALOG_GET_SERVICESPEC_BY_ID: "jms:queue:CATALOG.GET.SERVICESPEC_BY_ID"
CATALOG_GET_INITIAL_SERVICEORDERS_IDS: "jms:queue:CATALOG.GET.INITIAL_SERVICEORDERS"
CATALOG_GET_SERVICEORDER_IDS_BY_STATE: "jms:queue:CATALOG.GET.ACKNOWLEDGED_SERVICEORDERS"
CATALOG_ADD_SERVICE: "jms:queue:CATALOG.ADD.SERVICE"
CATALOG_UPD_SERVICE: "jms:queue:CATALOG.UPD.SERVICE"
CATALOG_GET_SERVICE_BY_ID: "jms:queue:CATALOG.GET.SERVICE"
CATALOG_GET_SERVICE_BY_ORDERID: "jms:queue:CATALOG.GET.SERVICE_BY_ORDERID"
CATALOG_SERVICE_QUEUE_ITEMS_GET: "jms:queue:CATALOG.SERVICEQUEUEITEMS.GET"
CATALOG_SERVICE_QUEUE_ITEM_UPD: "jms:queue:CATALOG.SERVICEQUEUEITEM.UPDATE"
CATALOG_SERVICE_QUEUE_ITEM_DELETE: "jms:queue:CATALOG.SERVICEQUEUEITEM.DELETE"
CATALOG_GET_PARTNER_ORGANIZATON_BY_ID: "jms:queue:CATALOG.GET.PARTNER_ORGANIZATION_BY_ID"
CATALOG_UPDATE_PARTNER_ORGANIZATION: "jms:queue:CATALOG.UPD.PARTNER_ORGANIZATION"
CATALOG_SERVICES_TO_TERMINATE: "jms:queue:CATALOG.GET.SERVICETOTERMINATE"
CATALOG_SERVICES_OF_PARTNERS: "jms:queue:CATALOG.GET.SERVICESOFPARTNERS"

CATALOG_GET_EXTERNAL_SERVICE_PARTNERS: "jms:queue:CATALOG.GET.EXTERNALSERVICEPARTNERS"
CATALOG_UPD_EXTERNAL_SERVICESPEC: "jms:queue:CATALOG.UPD.EXTERNAL_SERVICESPEC"

#ALARMS
ALARMS_ADD_ALARM: "jms:queue:ALARMS.ADD.ALARM"
ALARMS_UPDATE_ALARM: "jms:queue:ALARMS.UPDATE.ALARM"
ALARMS_GET_ALARM: "jms:queue:ALARMS.GET.ALARM"

#EVENT TOPICS IN Message Bus
EVENT_SERVICE_CREATE: "jms:topic:EVENT.SERVICE.CREATE"
EVENT_SERVICE_STATE_CHANGED: "jms:topic:EVENT.SERVICE.STATECHANGED"
EVENT_SERVICE_DELETE: "jms:topic:EVENT.SERVICE.DELETE"
EVENT_SERVICE_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICE.ATTRCHANGED"
EVENT_SERVICE_ORDER_CREATE: "jms:topic:EVENT.SERVICEORDER.CREATE"
EVENT_SERVICE_ORDER_STATE_CHANGED: "jms:topic:EVENT.SERVICEORDER.STATECHANGED"
EVENT_SERVICE_ORDER_DELETE: "jms:topic:EVENT.SERVICEORDER.DELETE"
EVENT_SERVICE_ORDER_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICEORDER.ATTRCHANGED"
EVENT_CUSTOMER_CREATE: "jms:topic:EVENT.CUSTOMER.CREATE"
EVENT_CUSTOMER_CHANGED: "jms:topic:EVENT.CUSTOMER.CHANGE"
EVENT_INDIVIDUAL_CREATE: "jms:topic:EVENT.INDIVIDUAL.CREATE"
EVENT_INDIVIDUAL_CHANGED: "jms:topic:EVENT.INDIVIDUAL.CHANGE"
EVENT_ORGANIZATION_CREATE: "jms:topic:EVENT.ORGANIZATION.CREATE"
EVENT_ORGANIZATION_CHANGED: "jms:topic:EVENT.ORGANIZATION.CHANGE"
EVENT_ALARM_CREATE: "jms:topic:EVENT.ALARM.CREATE"

#QUEUE MESSSAGES WITH VNFNSD CATALOG
NFV_CATALOG_GET_NSD_BY_ID: "jms:queue:NFVCATALOG.GET.NSD_BY_ID"

#MISC
GET_USER_BY_USERNAME: "jms:queue:GET.USER_BY_USERNAME"

#RESOURCES MESSAGES
CATALOG_ADD_RESOURCE: "jms:queue:CATALOG.ADD.RESOURCE"
CATALOG_UPD_RESOURCE: "jms:queue:CATALOG.UPD.RESOURCE"
CATALOG_GET_RESOURCE_BY_ID: "jms:queue:CATALOG.GET.RESOURCE"
EVENT_RESOURCE_CREATE: "jms:topic:EVENT.RESOURCE.CREATE"
EVENT_RESOURCE_STATE_CHANGED: "jms:topic:EVENT.RESOURCE.STATECHANGED"
EVENT_RESOURCE_DELETE: "jms:topic:EVENT.SERVICE.RESOURCE"
EVENT_RESOURCE_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.RESOURCE.ATTRCHANGED"
CATALOG_RESOURCES_OF_PARTNERS: "jms:queue:CATALOG.GET.SERVICESOFPARTNERS"

#LCM MESSAGES
CATALOG_GET_LCMRULE_BY_ID: "jms:queue:CATALOG.GET.LCMRULE"
CATALOG_GET_LCMRULES_BY_SPECID_PHASE: "jms:queue:CATALOG.GET.LCMRULES_BY_SPECID_PHASE"


#SERVICE_TEST
CATALOG_GET_SERVICETESTSPEC_BY_ID: "jms:queue:CATALOG.GET.SERVICETESTSPEC_BY_ID"
CATALOG_ADD_SERVICETEST: "jms:queue:CATALOG.ADD.SERVICETEST"
CATALOG_UPD_SERVICETEST: "jms:queue:CATALOG.UPD.SERVICETEST"
CATALOG_GET_SERVICETEST_BY_ID: "jms:queue:CATALOG.GET.SERVICETEST"

#NS ACTIONS
NFV_CATALOG_NSACTIONS_SCALE: "jms:queue:NSACTIONS.SCALE"
NFV_CATALOG_NS_LCMCHANGED: "jms:topic:NFV_CATALOG_NS_LCMCHANGED"

#RESERVATION_API
RESERVATION_CREATE: "jms:queue:RESERVATION.ADD"
RESERVATION_AVAILABILITY_CHECK: "jms:queue:RESERVATION.AVAILABILITYCHECK"

---


