server:
  port: 13082
  servlet:
    context-path : /tmf-api
spring:
  profiles: default
  application:
    name: openslice-service-catalog-management-api
  datasource:
    url: jdbc:mysql://localhost/ostmfdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: letmein0
    username: root
  jpa:
    database-platform: io.openslice.tmf.LocalMysqlDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext 
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true 
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100

logging:
  level:
    root: INFO
    portal.api: INFO
    org.springframework: INFO
    org.apache.camel: INFO 
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
    
swagger:
  authserver: "http://localhost:13081/osapi-oauth-server"
  clientid: "osapiWebClientId"
  clientsecret: "secret"
  
CATALOG_GET_SERVICEORDERS: "jms:queue:CATALOG.GET.SERVICEORDERS"
CATALOG_GET_SERVICEORDER_BY_ID: "jms:queue:CATALOG.GET.SERVICEORDER_BY_ID"
CATALOG_GET_SERVICESPEC_BY_ID: "jms:queue:CATALOG.GET.SERVICESPEC_BY_ID"
CATALOG_GET_INITIAL_SERVICEORDERS: "jms:queue:CATALOG.GET.INITIAL_SERVICEORDERS"
CATALOG_GET_ACKNOWLEDGED_SERVICEORDERS: "jms:queue:CATALOG.GET.ACKNOWLEDGED_SERVICEORDERS"
